# -*- coding: utf-8 -*-
"""Multiclass 02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAloLx5jRknezomyzN4Jz1DN0Zmk3efA
"""

import numpy as np
import matplotlib.pyplot as plt

N = 100 # number of points per class
D = 2 # dimensionality
K = 3 # number of classes
x = np.zeros((N*K,D)) # data matrix (each row = single example)
y = np.zeros(N*K, dtype='uint8') # class labels

for j in range(K):
  ix = range(N*j,N*(j+1))
  r = np.linspace(0.0,1,N) # radius
  t = np.linspace(j*4,(j+1)*4,N) + np.random.randn(N)*0.2 # theta
  x[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
  y[ix] = j

# Visualize
import matplotlib.pyplot as plt

def plot_predictions(x, y, title):
    """
    This function plots the model's predictions on the test data.
    """

    # Plotting predictions
    plt.figure(figsize=(10, 8))  # Set the figure size for better readability

    # Scatter plot for testing data predictions
    plt.scatter(
        x = x[:, 0],
        y = x[:, 1],
        c = y,
        cmap = plt.cm.coolwarm,
        edgecolor = 'w',
        linewidth = 1,
        s = 70,
        alpha = 0.6,
        label = "Test Predictions",
    )

    # Add a colorbar for predicted labels
    colorbar = plt.colorbar()
    colorbar.set_label(title, fontsize=12)
    colorbar.ax.tick_params(labelsize=10)

    # Titles and labels
    plt.title(title, fontsize=14)
    plt.xlabel("Feature 1", fontsize=12)
    plt.ylabel("Feature 2", fontsize=12)

    # Add legend
    plt.legend(loc="upper right")

    # Show the plot
    plt.tight_layout()
    plt.show()

# lets visualize the data:
plot_predictions(x, y, "Data")

import torch
from torch import nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

from sklearn.model_selection import train_test_split

x = torch.from_numpy(x).type(torch.float).to(device)
y = torch.from_numpy(y).type(torch.long).to(device) # `torch.Long` for the loss function

x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.20,
                                                    random_state = 42)

class MulticlassModel(nn.Module):

  def __init__(self, in_features, out_features, hidden_features = 8):
    super().__init__()
    self.in_features = in_features
    self.out_features = out_features
    self.hidden_features = hidden_features

    self.model = nn.Sequential(
        nn.Linear(in_features = self.in_features, out_features = self.hidden_features),
        nn.ReLU(),
        nn.Linear(in_features = self.hidden_features, out_features = self.hidden_features),
        nn.ReLU(),
        nn.Linear(in_features = self.hidden_features, out_features = self.out_features),
    ).to(device)

  def forward(self, x):
    return self.model(x)

model_0 = MulticlassModel(in_features = D,
                          out_features = K,
                          hidden_features = 16)

# Loss and Optimizer

loss_fn = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(params = model_0.parameters(),
                             lr = 0.1)

# Training Loop
from sklearn.metrics import classification_report

epochs = 100

for epoch in range(epochs):
  model_0.train()

  # Do the forward pass
  y_logits = model_0(x_train)

  # Calculate the loss
  loss = loss_fn(y_logits, y_train)

  # Optimizer zero grad
  optimizer.zero_grad()

  # Loss backward
  loss.backward()

  # Optimizer step, step, step
  optimizer.step()


  # Evalutaion time
  model_0.eval()
  with torch.inference_mode():
    # Do the forward pass
    test_logits = model_0(x_test)
    test_preds = torch.softmax(test_logits, dim = 1).argmax(dim = 1)

    # Calculate the loss
    test_loss = loss_fn(test_logits, y_test)

  # Watch it go down, down, down
  if epoch % 10 == 0:
    print(f"Epoch: {epoch} | Loss: {loss} | Test Loss: {test_loss}")

  if epoch == epochs-1:
    print(classification_report(y_true=y_test.cpu().numpy(),
                            y_pred=test_preds.cpu().numpy()))

# Plot the model predictions

import numpy as np
import matplotlib.pyplot as plt


# TK - this could go in the helper_functions.py and be explained there
def plot_decision_boundary(model, X, y):

    # Put everything to CPU (works better with NumPy + Matplotlib)
    model.to("cpu")
    X, y = X.to("cpu"), y.to("cpu")

    # Source - https://madewithml.com/courses/foundations/neural-networks/
    # (with modifications)
    x_min, x_max = X[:, 0].min() - 0.1, X[:, 0].max() + 0.1
    y_min, y_max = X[:, 1].min() - 0.1, X[:, 1].max() + 0.1
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 101),
                         np.linspace(y_min, y_max, 101))

    # Make features
    X_to_pred_on = torch.from_numpy(np.column_stack((xx.ravel(), yy.ravel()))).float()

    # Make predictions
    model.eval()
    with torch.inference_mode():
        y_logits = model(X_to_pred_on)

    # Test for multi-class or binary and adjust logits to prediction labels
    if len(torch.unique(y)) > 2:
        y_pred = torch.softmax(y_logits, dim=1).argmax(dim=1) # mutli-class
    else:
        y_pred = torch.round(torch.sigmoid(y_logits)) # binary

    # Reshape preds and plot
    y_pred = y_pred.reshape(xx.shape).detach().numpy()
    plt.contourf(xx, yy, y_pred, cmap=plt.cm.coolwarm, alpha=0.5)
    plt.scatter(X[:, 0], X[:, 1], c=y, s=40, cmap=plt.cm.coolwarm, alpha=0.7)
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())

# Plot decision boundaries for training and test sets
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.title("Train")

plot_decision_boundary(model_0, x_train, y_train)
plt.subplot(1, 2, 2)
plt.title("Test")
plot_decision_boundary(model_0, x_test, y_test)

with torch.inference_mode():
  y_logits = model_0(x_test)
  y_preds = torch.softmax(test_logits, dim = 1).argmax(dim = 1)


# Plotting predictions
plt.figure(figsize=(10, 8))  # Set the figure size for better readability

# Scatter plot for testing data predictions
plt.scatter(
    x = x_train[:, 0],
    y = x_train[:, 1],
    c = y_train,
    cmap = plt.cm.coolwarm,
    edgecolor = 'w',
    linewidth = 1,
    s = 70,
    alpha = 0.6,
    label = "Test Predictions",
)

# Scatter plot for testing data predictions
plt.scatter(
    x = x_test[:, 0],
    y = x_test[:, 1],
    c = y_preds,
    cmap = plt.cm.coolwarm,
    edgecolor = 'w',
    linewidth = 1,
    s = 70,
    alpha = 0.3,
    label = "Test Predictions",
)

# Add a colorbar for predicted labels
colorbar = plt.colorbar()
colorbar.set_label("Predictions", fontsize=12)
colorbar.ax.tick_params(labelsize=10)

# Titles and labels
plt.title("Predictions", fontsize=14)
plt.xlabel("Feature 1", fontsize=12)
plt.ylabel("Feature 2", fontsize=12)

# Add legend
plt.legend(loc="upper right")

# Show the plot
plt.tight_layout()
plt.show()

